---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: debian-7.8
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-6.6
  - name: centos-7.0

data_bags_path:    test/integration/data_bags/
roles_path:        test/integration/roles/
environments_path: test/integration/environments

suites:
  - name: server
    run_list:
      - role[bareos_server]
    attributes:
      bareos:
        dbpassword: 'ChangeMe1234#'

  - name: server-host-pools
    run_list:
      - role[bareos_server]
    attributes:
      bareos:
        host_pools: true
        custom_host_pools: true
