---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.6.0

platforms:
  - name: debian-7.8
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-6.7
  - name: centos-7.2
  - name: fedora-21
  - name: fedora-22

roles_path: test/integration/roles/

suites:

  - name: aio-server
    run_list:
      - role[bareos_director]
    attributes:
      bareos:
        test_mode: true
        server:
          conf:
            help: {
              test: '# Some String'
            }

  - name: tape-storage
    run_list:
      - role[bareos_director]
    attributes:
      bareos:
        test_mode: true
        storage:
          autochanger_enabled: true
        server:
          jobs: {
            unmanaged-host-job: {
              Description: '"Unmanaged Host Test Job"',
              Client: 'unmanaged-client-fd',
              JobDefs: 'default-def',
              Type: 'Backup'
            }
          }
