---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: debian-7.8
  - name: ubuntu-14.04
  - name: centos-6.6

data_bags_path:    test/integration/data_bags/
roles_path:        test/integration/roles/
environments_path: test/integration/environments

suites:
  - name: server
    run_list:
      - role[bareos_base]
      - recipe[bareos::database]
      - recipe[bareos::server]
      - recipe[bareos::storage]
      - recipe[bareos::workstation]
    attributes:
