---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: debian-7
    driver:
      box: debian-7-chef
  - name: ubuntu-12.04
    driver:
      box: ubuntu-12.04-chef
  - name: centos-6
    driver:
      box: centos-6-chef

data_bags_path:    test/integration/data_bags/
roles_path:        test/integration/roles/
environments_path: test/integration/environments

suites:
  - name: server
    run_list:
      - recipe[bareos::default]
      - recipe[bareos::database]
      - recipe[bareos::server]
      - recipe[bareos::storage]
      - recipe[bareos::workstation]
    attributes:
