---
driver:
  name: dokken

transport:
  name: dokken

provisioner:
  name: dokken
  multiple_converge: 2

platforms:
  - name: ubuntu-14
    driver:
      image: ubuntu-upstart:14.04
      privileged: true
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
  - name: centos-7
    driver:
      image: centos:7
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd
      intermediate_instructions:
        - RUN yum -y install lsof which systemd-sysv initscripts vixie-cron

verifier:
  name: inspec

suites:
  - name: bareos-aio-server
    run_list:
      - role[bareos_director]
    attributes:
      bareos:
        test_mode: true
        client:
          sensitive_configs: false
        storage:
          sensitive_configs: false
          autochanger_enabled: true
        director:
          sensitive_configs: false
          conf:
            help:
              test: '# Some String'
        workstation:
          sensitive_configs: false
        plugins:
          graphite:
            cron_job: true
            sensitive_configs: false
