---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: debian-7.8
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-6.7
  - name: centos-7.1
  - name: fedora-20
  - name: fedora-21

roles_path: test/integration/roles/

suites:
  - name: aio-server
    run_list:
      - role[bareos_director]
    attributes:
  - name: tape-storage
    run_list:
      - role[bareos_director]
    attributes:
      bareos:
        storage:
          autochanger_enabled: true
