---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: debian-7.8
    run_list:
      - recipe[apt]

  - name: ubuntu-12.04
    run_list:
      - recipe[apt]

  - name: ubuntu-14.04
    run_list:
      - recipe[apt]

  - name: centos-6.7

  - name: centos-7.0

  - name: fedora-20

  - name: fedora-21

data_bags_path:    test/integration/data_bags/
roles_path:        test/integration/roles/
environments_path: test/integration/environments

suites:
  - name: aio-server
    run_list:
      - role[bareos_server]
    attributes:

  - name: aio-server-pools
    run_list:
      - role[bareos_server]
    attributes:
      bareos:
        host_pools: '1'
