---
driver:
  name: vagrant

platforms:
  - name: debian-9
  - name: ubuntu-16.04
  - name: centos-6.9
    run_list:
      - recipe[yum-epel]
  - name: centos-7.4
    run_list:
      - recipe[yum-epel]

provisioner:
  name: chef_zero
  product_name: chef
  install_strategy: always
  product_version: "13.8.5"

verifier:
  name: inspec

suites:
  - name: bareos-aio-server
    run_list:
      - role[bareos_director]
    attributes:
      bareos:
        test_mode: true
        client:
          sensitive_configs: false
        storage:
          sensitive_configs: false
          autochanger_enabled: true
        director:
          sensitive_configs: false
          conf:
            help:
              test: '# Some String'
        workstation:
          sensitive_configs: false
        plugins:
          graphite:
            cron_job: true
            sensitive_configs: false
