AllCops:
  Exclude:
    - vendor/**

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
NumericLiterals:
  Enabled: false
SpaceBeforeFirstArg:
  Enabled: false
LineLength:
  Max: 180
FileName:
  Enabled: false
