language: ruby
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1

script:
  - bundle exec rspec --color --format progress
  - bundle exec foodcritic -f any --tags ~FC003 --tags ~FC015 --tags ~FC023 .
  - bundle exec rubocop

notifications:
  email:
    recipients:
      - ian.smith@pnnl.gov
    on_success: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8b3467fd343caf088255
    on_success: always
    on_failure: always
