dist: trusty
sudo: required
group: edge
services: docker
addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

install: echo "skip bundle install"

stages:
  - lint
  - test

env:
  - T=bareos-aio-server-ubuntu-14
  - T=bareos-aio-server-centos-7

script:
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen test $T -d always

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/rspec --version
  - /opt/chefdk/embedded/bin/chef gem install kitchen-dokken

jobs:
  include:
    - stage: lint
      env:
      script:
        - /bin/bash -xe travis/pre-commit.sh

notifications:
  email:
    recipients:
      # - leonard.tavae@gmail.com
      - gitbytes@gmail.com
    on_failure: never
    on_success: always
